### PR TITLE
Add Arabic Translation

### PR DESCRIPTION
**Pull request by karim88**
=== Arabic Translation ===

### CODE REVIEW

**Comment by pierremtb** [comment]
Thanks !

**Comment by karim88** [comment]
You're welcome!

**Comment by jmc-figueira** [comment]
Sorry if I'm wrong, but I believe the .pro file is missing the entry for this translation, is this correct?

**Comment by pierremtb** [comment]
@jmc-figueira Yes it's correct, i'll add it asap. But the most important part is the binary

**Pull request merged**
