### PR TITLE
Fix issue #89

### PR DESCRIPTION
**Pull request by Ilya87**

### CODE REVIEW

**Comment by tim-sueberkrueb** [comment]
@Ilya87 cool, thank you!

**Comment by tim-sueberkrueb** [comment]
@Ilya87 idk know why but it doesn't work for me, neither using make nor using QtCreator 0.0

**Comment by Ilya87** [comment]
I use aur build script and it works. Maybe your language file is outdated. Check please .ts file with qt linguist. Russian translation and .qm file are updated by me. Other qm files are untouched.

**Comment by Ilya87** [comment]
screen

**Comment by Ilya87** [comment]
LANGUAGE=de_DE liri-browser
screen

So, German translation should be loaded without problems. Translation file is simply outdated:

screen1

**Comment by tim-sueberkrueb** [comment]
@Ilya87 I'm sorry, you're right :) Thank you!

**Pull request merged**
